// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRfQYlf5m9fLbZxkMZv5MxmgpfdIiFh4Q',
    appId: '1:184869642934:web:1bc753d6b989d7ff59fc17',
    messagingSenderId: '184869642934',
    projectId: 'wishlist-nabila-ch',
    authDomain: 'wishlist-nabila-ch.firebaseapp.com',
    storageBucket: 'wishlist-nabila-ch.firebasestorage.app',
    measurementId: 'G-L7F9LSHDZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1vfXraItIP16HyBMkRZLQNUn19RG2lG8',
    appId: '1:184869642934:android:7f5a09926f05fff859fc17',
    messagingSenderId: '184869642934',
    projectId: 'wishlist-nabila-ch',
    storageBucket: 'wishlist-nabila-ch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6iccJpT-kjB4ljY27DEVe78lTn54Ed_U',
    appId: '1:184869642934:ios:b821f6963bbad81d59fc17',
    messagingSenderId: '184869642934',
    projectId: 'wishlist-nabila-ch',
    storageBucket: 'wishlist-nabila-ch.firebasestorage.app',
    iosBundleId: 'com.example.wishlistAppNabila',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6iccJpT-kjB4ljY27DEVe78lTn54Ed_U',
    appId: '1:184869642934:ios:b821f6963bbad81d59fc17',
    messagingSenderId: '184869642934',
    projectId: 'wishlist-nabila-ch',
    storageBucket: 'wishlist-nabila-ch.firebasestorage.app',
    iosBundleId: 'com.example.wishlistAppNabila',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRfQYlf5m9fLbZxkMZv5MxmgpfdIiFh4Q',
    appId: '1:184869642934:web:92814638ed38328859fc17',
    messagingSenderId: '184869642934',
    projectId: 'wishlist-nabila-ch',
    authDomain: 'wishlist-nabila-ch.firebaseapp.com',
    storageBucket: 'wishlist-nabila-ch.firebasestorage.app',
    measurementId: 'G-V1P145MQ9W',
  );

}